# Generated by Django 5.2 on 2025-05-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='page',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(upload_to='site_images/')),
                ('title', models.CharField(max_length=100)),
                ('second_title', models.CharField(max_length=50)),
            ],
        ),
    ]
