# Generated by Django 5.2 on 2025-05-28 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='second_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
