# Generated by Django 5.2 on 2025-06-02 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_page_second_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='Page_Button',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('href', models.CharField(max_length=100)),
                ('page_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.page')),
            ],
        ),
    ]
