# Generated by Django 5.2 on 2025-07-03 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_page_id_page_button'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallToAction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('content', models.CharField(max_length=200)),
                ('button', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='site_images/')),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='call_to_action',
            field=models.BooleanField(default=True),
        ),
    ]
