# Generated by Django 5.2 on 2025-07-16 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_calltoaction_page_call_to_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paragraph_Group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('order', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=45)),
                ('type', models.CharField(max_length=1)),
                ('page_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.page')),
            ],
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('order', models.IntegerField(unique=True)),
                ('type', models.CharField(max_length=1)),
                ('content', models.TextField()),
                ('paragraph_group_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.paragraph_group')),
            ],
        ),
    ]
