# Generated by Django 5.2 on 2025-07-17 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_paragraph_group_paragraph'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paragraph',
            name='type',
        ),
        migrations.AddField(
            model_name='paragraph',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='paragraph',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='Paragraph_Array',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('content', models.TextField(default='""')),
                ('paragraph_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.paragraph')),
            ],
        ),
    ]
